In [ ]:
import pandas as pd
hrrp = pd.read_csv("/content/hrrp_fy2026.csv")
hrrp.shape
hrrp.head()
hrrp.dtypes
print(hrrp["Number of Readmissions"].value_counts().head(10))
print(hrrp["Footnote"].value_counts(dropna=False))
pd.to_numeric(hrrp["Number of Readmissions"], errors="coerce").describe()

Number of Readmissions
Too Few to Report    3683
11                    318
14                    290
12                    263
15                    243
13                    236
17                    218
19                    213
18                    213
16                    211
Name: count, dtype: int64
Footnote
NaN     11343
5.0      3255
1.0      3150
29.0      377
7.0       205
Name: count, dtype: int64

   Start Date    End Date
0  07/01/2021  06/30/2024

In [ ]:
hosp = pd.read_csv("/content/hospital_general_info.csv")
hrrp["Facility ID"].isin(hosp["Facility ID"]).mean()
hrrp[["Start Date", "End Date"]].drop_duplicates()

   Start Date    End Date
0  07/01/2021  06/30/2024

In [ ]:
pd.to_numeric(hrrp["Number of Readmissions"], errors="coerce").describe()

count    8037.000000
mean       48.750653
std        49.758206
min        11.000000
25%        19.000000
50%        31.000000
75%        60.000000
max       847.000000
Name: Number of Readmissions, dtype: float64

In [ ]:
hosp = pd.read_csv("hospital_general_info.csv")
hrrp["Facility ID"].isin(hosp["Facility ID"]).mean()

np.float64(0.0)

In [ ]:
hrrp = pd.read_csv("hrrp_fy2026.csv", dtype={"Facility ID": str})
hosp = pd.read_csv("hospital_general_info.csv", dtype={"Facility ID": str})
hrrp["Facility ID"].isin(hosp["Facility ID"]).mean()

np.float64(0.9934533551554828)